### ISSUE TITLE
about few shot anomaly map

### ISSUE THREAD

**Issue by xbkaishui** [CASIA-IVA-Lab/AnomalyGPT#14]
Hi, 
Thanks for your great work. I have one question for the anomaly map , for few shot case, the anomaly map can't precise point which part is anomaly,  is there any method to refine the anomaly map
![截屏2023-09-08 17 28 25](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/1477791/857da1fb-bb79-4299-a7fd-9b0ecc09c3b5)

for the no shot case, the anomaly map is ok

**Comment by eichi7** [comment]
@xbkaishui please let me know how you change llama into  vicuna please

**Comment by FantasticGNU** [comment]
> Hi, Thanks for your great work. I have one question for the anomaly map , for few shot case, the anomaly map can't precise point which part is anomaly, is there any method to refine the anomaly map ![截屏2023-09-08 17 28 25](https://user-images.githubusercontent.com/1477791/266566946-857da1fb-bb79-4299-a7fd-9b0ecc09c3b5.png)
> 
> for the no shot case, the anomaly map is ok

Our current few-shot localizaiton result is based on the patch-level feature similarity between the query image and the normal image. Because there is no parameter training for the few-shot test samples, the localization result is not as accurate as the setting that has undergone unsupervised training. We will further improve this issue in our future work.
